# 1데이터 분석을 위한 주요 라이브러리

## 1.1 numpy


* 파이썬의 리스트는 여러 자료형의 값들을 하나의 변수에 저장할 수 있는 자료구조로서 강력하고 활용도가 높다

* 하지만 데이터를 처리할 때는 리스트와 리스트 간의 다양한 연산이 필요한데, 이러한 점에서 기능이 다소 부족하고, 연산 속도도 빠르지 않다. 따라서 데이터 과학자들은 넘파이 배열을 선호한다.

* 넘파이를 사용할 때는 반드시 넘파이 모듈을 import해야만 한다. 일반적으로 넘파이 모듈에 대해서는 엘리어스 np라는 별칭을 지정하여 사용한다.

* 배열 내부에는 항목(item)또는 원소(element)라는 값들로 구성된다.
*이 배열 내부의 각 요소는 인덱스라고 불리는 정수들로 참조된다.
*넘파이에서 차원은 축(axis)라고도 한다.
* 1d배열 형상(shape) 예시 = shape:(3,)
  2d배열 형상(shape) 예시 = shape:(2,3)
  3d배열 형상(shape) 예시 = shape:(4,3,2)


In [ ]:
import numpy as np

In [ ]:
a = np.array([2,3,4])

# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

* ndim 배열 축 혹은 차원의 개수를 나타냄.
* shape 배열의 형상을 기술, 튜플 형으로 나타냄.
* size 배열 원소의 개수를 말하며 (m,n)형상 배열의 size는 m*n
* dtype 배열 원소의 자료형을 기술함.
* itemsize 배열 원소의 크기를 바이트 단위로 기술함
* data 배열의 실제 원소를 포함하고 있는 버퍼
* stride 배열의 차원별로 다음요소로 점프하는데에 필요한 거리를 바이트로 표시한 값


In [ ]:
a = np.array([11,32,45])
b = np.array([5,6,7])
a + b


array([16, 38, 52])

In [ ]:
a / b

array([2.2       , 5.33333333, 6.42857143])

## 1.2 다차원 배열과 브로드캐스팅

* 넘파이는 a * 10을 수행할 때 np.array([10,20,30]) * np.array([10,10,10])와 같이 차원에 맞게, 스칼라 10을 벡터로 확장시켜주는 작업을 하는데 이를 브로드캐스팅이라고 한다.
* 스칼라 : 단일 차원의 값
* 벡터 : 한가지 스칼라 데이터타입으로 구성된 집합.
* 브로드캐스팅과 동시에 파이썬은 하나의 명령을 여러 데이터에 적용하여 병렬적으로 연산하는데 이것을 벡터화 연산이라고도 한다.

In [ ]:
a = np.array([10,20,30])
b = np.array([10,10,10])
a * b

array([100, 200, 300])

In [ ]:
b = np.array([[10,20,30],[40,50,60]])
c = np.array([2,3,4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [ ]:
b * c 

array([[ 20,  60, 120],
       [ 80, 150, 240]])

In [ ]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.full((4,4), 10)
a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
a = np.eye(4)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# np.eye와 브로드캐스팅 백터화연산 활용
a = np.eye(4)
a * 10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

1.3 연속적인 값을 가지는 다원 배열의 생성

In [ ]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
# 스텝값이 정수 자료형이 아니어도 가능하다
a = np.arange(1,11,0.2)
a

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8])

In [ ]:
a = np.arange(0.5,0.9,0.1)
a

array([0.5, 0.6, 0.7, 0.8])

In [ ]:
# linspace 함수는 지정된 구간에서 동일한 간격의 값을 지정된 횟수만큼 생성
# 시작값, 생성될 데이터의 마지막 값, 생성될 데이터의 

a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# 로그 스케일로 균등한 간격
a = np.logspace(0,5,6) # 10^0에서 10^5까지 6개의 수를 로그 스케일 균일한 간격으로 생성한다.
print(a)
np.log10(a) #a 배열에 로그를 취하면 0,1,2,3,4,5가 생성

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


array([0., 1., 2., 3., 4., 5.])

In [ ]:
a = np.linspace(0, np.sin(np.pi/2 * 2), 11)
a

array([0.00000000e+00, 1.22464680e-17, 2.44929360e-17, 3.67394040e-17,
       4.89858720e-17, 6.12323400e-17, 7.34788079e-17, 8.57252759e-17,
       9.79717439e-17, 1.10218212e-16, 1.22464680e-16])

## 1.3 다차원 배열의 축과 삽입


* 다 차원 배열의 형상 값에서 (3,)와 (1,3) 그리고 (3,1)의 차이를 제대로 이해하는 것은 중요하다.
* 여기서 (3,)은 축이 하나인 1차원 배열이고, (1,3),(3,1)은 모두 2차원 배열이다.
* 2차원 배열은 [[로 시작하여 ]]로 표시된다.

### 1.3.1 insert

In [ ]:
a = np.array([1,3,4])
np.insert(a,1,2) # a배열의 두 번쨰 원소(인덱스로 1)로 2를 삽입하고자 하면 insert함수 사용

array([1, 2, 3, 4])

In [ ]:
# 2차원 배열에 대해서 특정 값을 행과 열에 삽입.
b = np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, 4, axis=0)  #4라는 스칼라 값을 벡터값으로 브로드캐스팅

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [ ]:
b = np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, 4, axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [ ]:
b = np.array([[1,1],[2,2],[3,3]])
np.insert(b, 1, [1,2,3], axis = 1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 1.3.2 flip

In [ ]:
# 지정된 축방향으로 원소들을 뒤집기
c = np.array([[1,2,3],[4,5,6]])
np.flip(c, axis = 1)

array([[3, 2, 1],
       [6, 5, 4]])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
np.flip(c, axis = 0)

array([[4, 5, 6],
       [1, 2, 3]])

## 1.4 파이썬 리스트 vs 넘파이 다차원 배열


* 가장 큰 차이는 계산 성능
* 넘파이는 성능이 우수한 ndarray 객체를 제공
* 배열array은 동일한 자료형을 가진데이터를 연속으로저장
* 파이선의 리스트는 동일하지 않은 자료형을 가진 항목들을 담을 수 있다.
* 넘파이의 ndarray 객체는 동일한 자료형의 항목들만 저장한다. 이러한 차이로 넘파이가 원소에 접근하는 속도가 더 빠르다.
* 리스트는 데이터를 벡터의 개념으로ㅗ 해석하지 않고 단순히 여러 데이터가 나열된 것으로만 생각한다.
* 넘파이는 배열을 선형대수의 벡터 개념으로 다룬다.


In [ ]:
a = [1,2,3]
b = [10,20,30]
a+b

[1, 2, 3, 10, 20, 30]

In [ ]:
np_a = np.array(a)
np_b = np.array(b)
np_a + np_b

array([11, 22, 33])

* 두 리스트를 합치면 인덱스 별로 합산되지 않고 연결되어 버림
* 리스트를 이루는 원소들의 인덱스가 특별한 의미를 갖지 않고 단순히 하나의 리스트 내에서 순서만을 나타내는 것으로 간주하기 때문

* 이와는 반대로, 넘파이는 대응되는 인덱스들이 더해지고 뺄 수 있는 연관된 데이터라고 가정한다. 데이터를 벡터로 간주하는 것이다.

* 다차원 배열 내의 원소는 인덱스라고 불리는 정수를 사용하여 참조할 수 있다.
* 리스트에서 사용했던 인덱싱과 슬라이싱은 넘파이 배열에도 거의 동일하게 적용된다.
* 1차원 배열의 인덱싱과 슬라이싱은 리스트와 큰 차이가 없으므로 2차원 배열을 이용하여 기본적인 인덱싱과 슬라이싱을 연습한다.

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [ ]:
print(arr_2d[0][0])
print(arr_2d[2])

1
[7 8 9]


## 1.5 다차원 배열의 최대값, 최소값, 평균값 구하기와 정렬

In [ ]:
a = np.array([10,20,30])
a.max(), a.min(), a.mean()

(30, 10, 20.0)

In [ ]:
a.astype(np.float64)

array([10., 20., 30.])

### 1.5.1 flatten
* 다차원 배열이 2차원 이상의 배열이라면 이를 1차원 배열로 변환할 필요성도 있는데 이때 사용하는 메소드가 바로 flatten()메소드이다.
이 과정을 평탄화라고 한다.

In [ ]:
b = np.array([[1,1],[2,2],[3,3],[4,4]])
b.flatten()

array([1, 1, 2, 2, 3, 3, 4, 4])

### 1.5.2 전치
* 2차원 배열의 행과 열의 순서를 서로 교환하는 것을 전치transpose라고 하는데 다차원 배열의 전치는 T. 속성값을 이용하면 된다.

In [ ]:
b = np.array([[1,1],[2,2],[3,3],[4,4]])
b.T

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### 1.5.3 sort

In [ ]:
c = np.array([43,5,42,21,76])
c.sort()
print(c[::-1]) #내림차순
print(c)

[76 43 42 21  5]
[ 5 21 42 43 76]


In [ ]:
# 2차원 배열이 있을 때 sort메소를 사용하면 axis1 방향으로 오름차순 정렬
# 키워드 인자로 axis=0을 넣어주면 axis0의 방향으로 오름차순 정렬이 된다.
d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort()
print(d)

d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort(axis=0)
print(d)

[[24 35 55]
 [ 9 19 69]
 [ 1  4 11]]
[[ 4  1  9]
 [35 19 11]
 [69 24 55]]


In [ ]:
d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort()
print(np.flip(d, axis=1))

d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort(axis=0)
print(np.flip(d,axis=0))

[[55 35 24]
 [69 19  9]
 [11  4  1]]
[[69 24 55]
 [35 19 11]
 [ 4  1  9]]


## 1.6 다차원 배열을 위한 APPEND()함수와 행렬 곱셈

* append()함수는 인자로 입련된 두 배열을 합하는 일을 하는데 axis를 통해서 축을 명시하지 않으면 디폴트 형상인 1차원 배열로 변환하게 된다.

* 이때 axis=0과 같이 축을 명시해 준다면 다음과 같이 특정한 축으로 합하게 되어 배열의 차원이 유지된다.
* append 함수의 큰 특징은 axis를 명시하면 values의 차원의 수와 arr의 차원의 수가 동일

### 1.6.1 append

In [ ]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append([a],b,axis=0) #[a]를 통해 2차원 배열로 만들어야함

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append([a],b,axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append(b, [a], axis =0)

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [ ]:
np.append(b, [[3],[3]], axis=1)

array([[4, 5, 6, 3],
       [7, 8, 9, 3]])

1.6.2 matmul() 행렬곱
* 조금 더 편리하게 사용할 수 있는 것이 @연산자.

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,20],[30,40]])
a*b

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
np.matmul(a,b)

array([[ 70, 100],
       [150, 220]])

## 1.7 난수
* 실세계와 유사한 특성을 가지는 가상의 데이터를 만들어서 분석하고 시뮬레이션을 한 후에 이 모델을 실세계 데이터 분석에 적용하는 경우가 많다.
* 난수란 인간의 의도와 무관하게 생성된 수. 인간이 만든 기계에 특정한 알고리즘을 통해서 난수를 생성한다는 것 자체가 모순.
* 하지만 난수와 유사한 특징을 가지는 수를 생성하는 것은 가능. 이러한 난수를 의사난수.
* 의사난수생서기의 특징은 이 생성기가 만들어낸 임의의 난수값 Xn을 다음 난수 값 Xn+1을 만드는 재료로 사용한다는 점.
* 의사 난수 생성기의 예
  Xn+1 = (a * Xn+ b) mod m

In [ ]:
def pseudo_rand(x):
  a = 1103515245
  b = 12345
  m = 231
  new_x = (a * x + b) % m
  return new_x

* 난수를 생성하는 코드에는 다음 난수를 생성하기 위한 최초 값이 필요한데 이를 씨드 값이라고 한다.
* 보통 시드값은 컴퓨터로 부터 시간 정보를 얻어서 이값을 사용하는 경우가 많다.

In [ ]:
height = np.random.randint(150,190,size=10) #190 미포함.
height

array([171, 183, 162, 151, 152, 167, 189, 179, 178, 158])

In [ ]:
height = np.random.randint(150,190,size=(3,10)) #190 미포함.
height

array([[161, 169, 153, 189, 170, 153, 188, 156, 160, 153],
       [173, 181, 150, 167, 176, 156, 169, 150, 167, 177],
       [159, 181, 167, 187, 159, 189, 152, 178, 182, 185]])

In [ ]:
#randn() 평균이 0이고 분산이 1인 표중정규분포
rnd = np.random.rand(5) * 10 + 165 # 평균값이 165, 표준편차가 10인 값 생성.
rnd

array([170.83262976, 167.62020802, 173.31954307, 172.77534255,
       166.88908426])

In [ ]:
rnd.round(2)

array([170.83, 167.62, 173.32, 172.78, 166.89])

random 서브 모듈에 포함된 난수 관련 함수
* rand() 균등분포의 난수 표본을 추출한다
* randn() 표준 정규 분포의 난수 표본을 추출한다.
* randint() 최소값과 최대값을 인자로 받아, 주어진 범위 내의 정수 난수를 생성한다
* normal() 평균과 표준편차를 인자로 받아, 정규 분포의 난수 표본을 추출
* uniform() 균등분포에서 표본을 추출한다.
* shuffle() 주어진 리스트나 다차원 배열의 순서를 임의로 섞는다.
* permutation() 주어진 범위의 수를 생썽하여 섞거나, 배열을 임의의 순서로 섞는다.

In [ ]:
a = np.arange(10)
np.random.shuffle(a)
a

array([7, 9, 1, 2, 8, 0, 3, 6, 4, 5])

In [ ]:
a = np.arange(1,51)
np.random.shuffle(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
def train_test_split(x):
  n = int(x.size)
  n1 = int(n * (0.8))
  n2 = int(n * (0.2))
  train_data = np.array(x[0:n1])
  test_data = np.array(x[n1:])
  return train_data, test_data

In [ ]:
b,c = train_test_split(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[41 42 43 44 45 46 47 48 49 50]


## 1.8 넘파이 스타일의 슬라이싱과 논리 인덱싱
* 넘파이 스타일의 인덱싱을 이용하여 슬라이싱을 하면 각각의 슬라이싱 범위는 리스트의 슬라이싱처럼 순차적으로 적용되는 것이 아니라, 각각의 축에 별도로 적용된다.

In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [0,1,2]])

arr_2d[1: ,0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [ ]:
# 논리 인덱싱
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [0,1,2]])
arr_2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [ ]:
arr_2d[ arr_2d % 2 == 0]

array([2, 4, 6, 8, 0, 2])

## 1.9 리덕션
* 리덕션이라는 것은 여러 개의 수로 이루어진 배열을 하나의 수로 집계하는 것이다.
* 넘파이는 이 집계를 위한 함수로 sum(), mean(), max(), min()같은 함수를 제공한다.
* 축을 매개변수로 줄 수 있다.

In [ ]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

np.sum(arr, axis = (0,1)) #axis = (0,1)은 생략가능
print(np.sum(arr))
print(np.mean(arr, axis = 1))

[ 5 10 15 20 25]
[15 15 15 15 15]
75
[3. 3. 3. 3. 3.]


In [ ]:
import time

n = 1000
arr = np.random.rand(n,n)

sum_naive = 0
start = time.time()
for i in range(n):
  for j in range(n):
    sum_naive += arr[i,j]

end = time.time()
print(n, 'x', n,"배열의 원소합", sum_naive, "\n계산 시간: ",end - start)

1000 x 1000 배열의 원소합 500191.8004662017 
계산 시간:  0.3085205554962158


## 1.10 선형방정식
* 연립 방정식이 해를 가지는 경우도 있지만 그렇지 않은 경우도 있다. 이를 판별하기 위해서는 행렬식을 이용할 수 있다.
*행렬식은 정방 행렬에 수를 대응시키는 함수인데, 연립 방정식이 해를 가지는지 아닌지를 판별하는 데 사용할 수 있다.

In [ ]:
a = np.array([[2,1],[4,5]])
det_a = np.linalg.det(a) # a행렬의 행렬식
b = np.array([[1,2],[3,-6]])
det_b = np.linalg.det(b) # b행렬의 행렬식
print(det_a, det_b)

6.0 -12.0


In [ ]:
a = np.array([[1,1,-1],
              [2,-1,3],
              [1,2,1]])
b = np.array([0,9,8])
c = np.linalg.solve(a,b)
print(c)

[1. 2. 3.]


In [ ]:
a = np.array([[1,1,-1],
              [2,-1,3],
              [1,2,1]], dtype = 'int32')
print("det(A) = {0:.1f}".format(np.linalg.det(a)))

det(A) = -11.0


## 1.11 배열의 결합
* concatenate
* 리스트를 결합하기 위해서는 + 연산자를 사용할 수 있으나 다차원 배열의 +는 두배열의 원소 합이 되므로 이 연산자 대신 다음과 같이 넘파이의 concatenate()함수를 사용해서 두 배열을 결합할 수 있다.
* vstack
* 수직
* hstack
* 수평

In [ ]:
a = np.arange(10,18).reshape(2,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c = np.arange(8).reshape(2,4)
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
d = list(range(4))
d

[0, 1, 2, 3]

In [ ]:
# concatenate
np.concatenate((a,b)) #a배열의 마지막 원소 다음에 b배열을 넣는다.

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# vstack
np.vstack((a,d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [ ]:
np.vstack((a,b,d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [ ]:
# hstack
np.hstack((a,c))

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [ ]:
#np.hstack((a,b)) (2,4), (3,4) 배열은 수평결합이 안됨. 벨류에러 발생


### 1.11.1 배열을 결합하는 R_,C_클래스와 column_stack()함수

* 여러 개의 다차원 배열을 결합하는 또 다른 방법

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([[1, 2 , 3],
              [4, 5, 6]])
d = np.array([[10,20,30],
              [40,50,60]])

In [ ]:
np.r_[a,b]

array([ 1,  2,  3, 10, 20, 30])

In [ ]:
np.r_[[a],[b]]

array([[ 1,  2,  3],
       [10, 20, 30]])

In [ ]:
np.r_[a, 4, 5, 6, b]

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [ ]:
np.c_[a,b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.c_[[a],[b]]

array([[ 1,  2,  3, 10, 20, 30]])

In [ ]:
np.r_[[0]*3, 5, 6]

array([0, 0, 0, 5, 6])

In [ ]:
np.r_[c, d]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.r_[a.reshape(-1,1), b.reshape(-1,1)]

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [ ]:
np.concatenate((a.reshape(-1,1), b.reshape(-1,1)), axis = 1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.c_[a,b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.c_[c,d]

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])